### [Reading Material Github Link]( https://github.com/bansalkanav/Machine_Learning_and_Deep_Learning/blob/master/Module%202%20-%20Python%20for%20Data%20Science/1.%20Numpy/numpy.ipynb)

## `Arrays`
[Question Link](https://www.hackerrank.com/challenges/np-arrays/problem)

In [13]:
import numpy

def arrays(arr):
    arr = [float(i) for i in arr]
    arr.reverse()
    return (numpy.array(arr))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

2 3 6 5 8 9
[9. 8. 5. 6. 3. 2.]


## `Shape and Reshape`
[Question Link](https://www.hackerrank.com/challenges/np-shape-reshape/problem)

In [14]:
import numpy
nums = list(map(int,input().split()))
numpy.array(nums)
print(numpy.reshape(nums,(3,3)))

2 3 6 5 2 4 7 8 9
[[2 3 6]
 [5 2 4]
 [7 8 9]]


## `Transpose and Flatten`
[Question Link](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem)

In [28]:
import numpy
lst = []
N,M = list(map(int,input().split()))
for i in range(N):
    lst.append(list(map(int,input().split())))
lst = numpy.array(lst)
print(numpy.transpose(lst))
print(lst.flatten())

2 2
1 2
3 8
[[1 3]
 [2 8]]
[1 2 3 8]


## `Concatenate`
[Question Link](https://www.hackerrank.com/challenges/np-concatenate/problem)

In [ ]:
import numpy
np = []
mp = []
N,M,P =list(map(int,input().split()))
for i in range(N):
    np.append(list(map(int,input().split())))

for i in range(M):
    mp.append(list(map(int,input().split())))

print(numpy.concatenate((np,mp)))

## `Zeros and Ones`
[Question Link](https://www.hackerrank.com/challenges/np-zeros-and-ones/problem)

In [30]:
import warnings
warnings.filterwarnings('ignore')
import numpy

tup = tuple(map(int,input().split()))
print(numpy.zeros(tup,dtype=numpy.int))
print(numpy.ones(tup,dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## `Eye and Identity`
[Question Link](https://www.hackerrank.com/challenges/np-eye-and-identity/problem)

In [31]:
import numpy
numpy.set_printoptions(legacy='1.13')   # In order to get alignment correct,
N,M = list(map(int,input().split()))
print(numpy.eye(N,M,0))

4 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]


## `Array Mathematics`
[Question Link](https://www.hackerrank.com/challenges/np-array-mathematics/problem)

In [37]:
import numpy

N,M = list(map(int,input().split()))    # N x M
A = numpy.array([int(i) for i in input().split()])
B = numpy.array([int(i) for i in input().split()])
print(A+B)
print(A-B)
print(A*B)
print((A/B).astype(numpy.int))
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0 0 0 0]
[1 2 3 4]
[    1    64  2187 65536]


In [38]:
import numpy as np
dim=list(map(int,input().split()))
lst1=[]
lst2=[]
for i in range(dim[0]):
    lst1.append(list(map(int,input().split())))
for i in range(dim[0]):
    lst2.append(list(map(int,input().split())))
A=np.array(lst1,dtype=int)
B=np.array(lst2,dtype=int)
print(A+B)
print(A-B)
print(A*B)
print((A/B).astype(np.int))
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## `Floor, Ceil and Rint`
[Question Link](https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem)

In [40]:
import numpy
numpy.set_printoptions(legacy='1.13')
A = numpy.array(list(map(float,input().split())))
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## `Sum and Prod`
[Question Link](https://www.hackerrank.com/challenges/np-sum-and-prod/problem)

In [45]:
import numpy
mat = []
N,M = list(map(int,input().split()))
for i in range(N):
    mat.append(list(map(int,input().split())))
mat = numpy.array(mat)
print(numpy.prod(numpy.sum(mat,axis=0)))

2 2 
1 2 3 4
4 5 6 7
3465


## `Min and Max`
[Question Link](https://www.hackerrank.com/challenges/np-min-and-max/problem)

In [47]:
import numpy
arr = []
N,M = list(map(int,input().split()))
for i in range(N):
    arr.append(list(map(int,input().split())))
arr = numpy.array(arr)
print(numpy.max(numpy.min(arr,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


## `Mean, Var, and Std`
[Question Link](https://www.hackerrank.com/challenges/np-mean-var-and-std/problem)

In [48]:
import numpy
arr = []
N,M = list(map(int,input().split()))
for i in range(N):
    arr.append(list(map(int,input().split())))
arr = numpy.array(arr)
print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(numpy.round(numpy.std(arr,axis=None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## `Dot and Cross *****`
[Question Link](https://www.hackerrank.com/challenges/np-dot-and-cross/problem)
- Matrix multiplication of A and B means dot product of A and B

In [4]:
import numpy as np
n=int(input())
lst1=[]
lst2=[]
for i in range(n):
        lst1.append(list(map(int,input().split())))
for i in range(n):
        lst2.append(list(map(int,input().split())))
A=np.array(lst1)
B=np.array(lst2)
print(np.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## `Inner and Outer *****`
[Question Link](https://www.hackerrank.com/challenges/np-inner-and-outer/problem)

In [8]:
import numpy
A = numpy.array(list(map(int,input().split())))
B = numpy.array(list(map(int,input().split())))
print(numpy.inner(A,B))
print(numpy.outer(A,B))

print(numpy.dot(A,B))
print(numpy.cross(A,B))
## inner product and dot product are same in some cases

1 2 3
4 5 6
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32
[-3  6 -3]


## `Linear Algebra *****`
- The NumPy module also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg.
- [Question Link](https://www.hackerrank.com/challenges/np-linear-algebra/problem)

In [17]:
import numpy
arr = []
n = int(input())
for i in range(n):
    arr.append(list(map(float,input().split())))
print(numpy.round_(numpy.linalg.det(numpy.array(arr)),2))

2
1.1 1.1
1.1 1.1
0.0


## `Polynomials *****`
[Question Link](https://www.hackerrank.com/challenges/np-polynomials/problem)

In [16]:
import numpy
coeff = numpy.array(list(map(float,input().split())))
x = float(input())
print(numpy.polyval(coeff, x))

1.1 2 3
0
3.0


## `End of Task6 -------------------------------`